---
abstract: 'Perl6 like method signature parser'
author:
  - 'Ash Berlin <ash@cpan.org>.'
build_requires:
  Test::Exception: 0
  Test::More: 0
  aliased: 0
distribution_type: module
generated_by: 'Module::Install version 0.770'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-Method-Signatures
no_index:
  directory:
    - inc
    - t
requires:
  List::MoreUtils: 0
  Moose: 0
  MooseX::Traits: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0
  Text::Balanced: 2
  namespace::clean: 0
resources:
  homepage: http://github.com/ashb/parse-method-signatures/tree/master
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ashb/parse-method-signatures.git
version: 1.001000
